# Generated by Django 5.0.7 on 2024-08-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='admin_password',
            new_name='password',
        ),
    ]
