# Generated by Django 5.0.7 on 2024-08-06 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Create_at', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(default='active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('Address_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Pincode', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('Review_id', models.AutoField(primary_key=True, serialize=False)),
                ('Review_Comments', models.CharField(max_length=255)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productdetails')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateField(auto_now_add=True)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productdetails')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.productdetails')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
        ),
    ]
